author: "Tobe O <thosakwe@gmail.com>"
description: "Example app built with vanilla Dart and angel_route."
homepage: "https://github.com/angel-example/router.git"
name: "example_router"
version: "1.0.0"
dependencies: 
  angel_route: "^1.0.0-dev+17"
dev_dependencies: 
  browser: "^0.10.0+2"
  dart_to_js_script_rewriter: "^1.0.2"
